"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetTimeRequest(_message.Message):
    """client 送出的請求（不需要任何參數）"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTimeRequest: _TypeAlias = GetTimeRequest  # noqa: Y015

@_typing.final
class GetTimeResponse(_message.Message):
    """server 回傳的時間資訊"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    UNIX_SECONDS_FIELD_NUMBER: _builtins.int
    UNIX_NANOS_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    HOSTNAME_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.str
    """ISO 8601 格式，例如 "2026-06-20T10:30:00+00:00" """
    unix_seconds: _builtins.int
    """Unix timestamp（秒）"""
    unix_nanos: _builtins.int
    """奈秒部分（來自 time.time_ns）"""
    timezone: _builtins.str
    """主機時區，例如 "Asia/Taipei" """
    hostname: _builtins.str
    """Pod / 主機名稱"""
    def __init__(
        self,
        *,
        timestamp: _builtins.str = ...,
        unix_seconds: _builtins.int = ...,
        unix_nanos: _builtins.int = ...,
        timezone: _builtins.str = ...,
        hostname: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hostname", b"hostname", "timestamp", b"timestamp", "timezone", b"timezone", "unix_nanos", b"unix_nanos", "unix_seconds", b"unix_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTimeResponse: _TypeAlias = GetTimeResponse  # noqa: Y015
