"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import time_service_pb2 as _time_service_pb2
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class TimeServiceStub:
    """TimeService exposes the Raspberry Pi system clock over gRPC."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> TimeServiceAsyncStub: ...
    GetTime: _grpc.UnaryUnaryMultiCallable[_time_service_pb2.GetTimeRequest, _time_service_pb2.GetTimeResponse]

@_typing.type_check_only
class TimeServiceAsyncStub(TimeServiceStub):
    """TimeService exposes the Raspberry Pi system clock over gRPC."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetTime: _aio.UnaryUnaryMultiCallable[_time_service_pb2.GetTimeRequest, _time_service_pb2.GetTimeResponse]  # type: ignore[assignment]

class TimeServiceServicer(metaclass=_abc_1.ABCMeta):
    """TimeService exposes the Raspberry Pi system clock over gRPC."""

    @_abc_1.abstractmethod
    def GetTime(
        self,
        request: _time_service_pb2.GetTimeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_time_service_pb2.GetTimeResponse, _abc.Awaitable[_time_service_pb2.GetTimeResponse]]: ...

def add_TimeServiceServicer_to_server(servicer: TimeServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
