# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: time_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'time_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12time_service.proto\x12\x0ctime_service\"\x10\n\x0eGetTimeRequest\"r\n\x0fGetTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x14\n\x0cunix_seconds\x18\x02 \x01(\x03\x12\x12\n\nunix_nanos\x18\x03 \x01(\x05\x12\x10\n\x08timezone\x18\x04 \x01(\t\x12\x10\n\x08hostname\x18\x05 \x01(\t2U\n\x0bTimeService\x12\x46\n\x07GetTime\x12\x1c.time_service.GetTimeRequest\x1a\x1d.time_service.GetTimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTIMEREQUEST']._serialized_start=36
  _globals['_GETTIMEREQUEST']._serialized_end=52
  _globals['_GETTIMERESPONSE']._serialized_start=54
  _globals['_GETTIMERESPONSE']._serialized_end=168
  _globals['_TIMESERVICE']._serialized_start=170
  _globals['_TIMESERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
